### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/pidgin-xmpp-ignore-groups#4]
```
several people have problems compiling correctly this plugin.

In comment #4 of Issue 1, I have provided a working makefile which solves this 
problem.

Dear eionrobb, would you kindly add this Makefile to the source, please ?

Thank you very much.

```

Original issue reported on code.google.com by `doktor....@gmail.com` on 27 Mar 2013 at 7:04

Attachments:
* [Makefile](https://storage.googleapis.com/google-code-attachments/pidgin-xmpp-ignore-groups/issue-4/comment-0/Makefile)

**Comment by EionRobb** [comment]
I finally added the Makefile :)
