### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by micwoj92** [EionRobb/pidgin-xmpp-ignore-groups#8]
Asking because in readme it says facebook xmpp but it doesnt use xmpp since like 2015.

**Comment by EionRobb** [comment]
lol fair enough, I'll update the readme :)

To be fair though, the XMPP protocol has been stable enough that it hasn't needed any changes to the plugin to continue to work

**Comment by micwoj92** [comment]
Thanks for quick response, that means that #6 and #5 should be closed.
